### ISSUE TITLE
Error on docker startup

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/activeTransportToolbox#2]
I suspect we will develop a new repo for the next phase but, FYI @layik  and @mpadge, could not reproduce the app and got the following message when building from the latest version:

```
docker run --rm -p 8000:8000 atfutures/att

[1] "Loading /app/data-intermediate/flows/accra/flow_foot_activity_bus.Rds ..."
Error in sf::st_sf(g$dat, geometry = g$geoms) : 
  no simple features geometry column present
Calls: <Anonymous> ... withVisible -> eval -> eval -> processRDS -> <Anonymous>
Execution halted
```

**Comment by mpadge** [comment]
ah, that'd be my fault there - updated `dodgr` likely no longer works with that old code. Give me a mo ...

**Comment by Robinlovelace** [comment]
No probs - I suggest we start from scratch...
